name: cook_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pancakes.jpg
    - assets/icons/search.svg
    - assets/icons/search-interface-symbol.png
    - assets/icons/edit.png
    - assets/
    
